name: wonder_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  responsive_sizer: ^3.1.1
  google_fonts: ^3.0.1
  otp_text_field: ^1.1.3
  flutter_slidable: ^2.0.0
  photo_view: ^0.14.0
  http: ^0.13.5
  image_picker: ^0.8.6+1
  top_snackbar_flutter: ^3.0.0+1
  motion_toast: ^2.6.4
  shared_preferences: ^2.0.17
  star_rating: ^0.10.0
  intl: ^0.18.0
  auto_size_text: ^3.0.0
  lottie: ^2.2.0

  google_maps_flutter: ^2.2.3
  google_maps_place_picker_mb: ^3.0.0
  image: ^4.0.13
  flutter_image_compress: ^1.1.3
 
 
dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/images/  
              
 
      
          