name: wonder_app
version: 1.0.20+21
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.6'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: 
  otp_text_field: ^1.1.3
  flutter_slidable: ^2.0.0
  photo_view: ^0.14.0
  flutter_svg: ^1.1.6
  http: ^0.13.5
  image_picker: ^0.8.6+1
  top_snackbar_flutter: ^3.0.0+1
  motion_toast: ^2.6.4
  shared_preferences: ^2.0.17
  star_rating: ^0.10.0
  intl: ^0.18.0
  auto_size_text: ^3.0.0
  lottie: ^2.2.0
  firebase_messaging: ^14.2.3
  firebase_core: ^2.6.0
  flutter_local_notifications: ^13.0.0
  flutter_tts: ^3.6.3
  google_maps_flutter: ^2.2.3
  google_maps_place_picker: ^2.1.0-nullsafety.3
  image: ^4.0.13
  flutter_image_compress: ^1.1.3
  razorpay_flutter: ^1.3.0
  flutter_widget_from_html_core: ^0.10.0
  dotted_border: ^2.0.0+3
  url_launcher: ^6.1.9
  flutter_secure_storage: ^8.0.0
  image_cropper: ^4.0.1
  rflutter_alert: ^2.0.4
  upgrader: ^4.8.1
  flutter_cache_manager: ^3.3.0
  pinch_zoom: ^1.0.0
  text_to_speech: ^0.2.3
  paginated_search_bar: ^1.1.1
  infinite_scroll_pagination: ^3.2.0
  pull_to_refresh: ^2.0.0
  shimmer_animation: ^2.1.0+1
  video_player: ^2.7.0
 
  cloud_firestore: ^4.8.2
  chewie: ^1.2.2
  chat_bubbles: ^1.4.1
  responsive_sizer: ^3.1.1
  firebase_database: ^10.2.4
 
dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/images/  
  - assets/images/drawer/
  - assets/images/wonder_list/
  - assets/images/bottom/
              
 
      
          